for %{arm} with hardfloat pass -mfloat-abi=hard to clang invoked by bindgen
it appears that libclang preprocessing uses some minimal platform
configuration which for %{arm} means soft float causing error on hard
float targets:

/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-soft.h' file not found
panicked at 'Unable to generate bindings: ClangDiagnostic("/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-soft.h' file not found\n")', bindgen-cli/main.rs:52:36